name: Container Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy-production:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    environment: production
    steps:
      - name: Deploy Production
        run: |
          echo "Deploying production from main branch..."
          sudo container-web-deploy production-api ghcr.io/${{ github.repository }}:main \
            -e APP_MODE=production \
            -e API_TOKEN=${{ secrets.API_TOKEN }}

  deploy-development:
    needs: build-and-push
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    environment: development
    steps:
      - name: Deploy Development
        run: |
          echo "Deploying development from dev branch..."
          sudo container-web-deploy dev-api ghcr.io/${{ github.repository }}:dev \
            -e APP_MODE=development \
            -e API_TOKEN=${{ secrets.API_TOKEN }}
