name: Build and Deploy API

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying production from main branch..."
          sudo container-web-deploy production-api ghcr.io/${{ github.repository }}:main

      - name: Deploy Development
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Deploying development from dev branch..."
          sudo container-web-deploy dev-api ghcr.io/${{ github.repository }}:dev
